name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup stable Rust and components
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Print Rust version
      run: rustc --version

    - name: Build (default)
      run: cargo build --all-targets --verbose

    - name: Build (all features)
      run: cargo build --all-features --all-targets --verbose

    - name: Run tests (all features)
      run: cargo test --all-features --verbose

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy --all-features --all-targets
